# Generated by Django 4.2.7 on 2023-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='name',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='image',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
