# Generated by Django 4.2.7 on 2023-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, default='/static/images/default-avatar.jpg', max_length=254, null=True),
        ),
    ]
