# Generated by Django 4.2.7 on 2023-11-26 08:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('address', models.CharField(max_length=100, null=True)),
                ('number_of_employees', models.IntegerField(default=0, null=True)),
                ('social_link', models.CharField(max_length=254, null=True)),
                ('industry', models.CharField(max_length=50, null=True)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
